Traceback (most recent call last):
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/envs/engr131/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/envs/engr131/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import shutil

shutil.copyfile('./MyTestFile copy.txt', './MyTestFile.txt')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[29], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mshutil[39;00m
[0;32m----> 3[0m [43mshutil[49m[38;5;241;43m.[39;49m[43mcopyfile[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m./MyTestFile copy.txt[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m./MyTestFile.txt[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/conda/envs/engr131/lib/python3.10/shutil.py:254[0m, in [0;36mcopyfile[0;34m(src, dst, follow_symlinks)[0m
[1;32m    252[0m     os[38;5;241m.[39msymlink(os[38;5;241m.[39mreadlink(src), dst)
[1;32m    253[0m [38;5;28;01melse[39;00m:
[0;32m--> 254[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43msrc[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mrb[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m fsrc:
[1;32m    255[0m         [38;5;28;01mtry[39;00m:
[1;32m    256[0m             [38;5;28;01mwith[39;00m [38;5;28mopen[39m(dst, [38;5;124m'[39m[38;5;124mwb[39m[38;5;124m'[39m) [38;5;28;01mas[39;00m fdst:
[1;32m    257[0m                 [38;5;66;03m# macOS[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './MyTestFile copy.txt'

